server:
  port: 3344
spring:
  application:
    name: SPRING-CLOUD2019-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gssnb/spring-cloud2019-config.git
          username: ------------
          password: ------------