server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   # mybatis 的配置文件所在路径
  type-aliases-package: cn.fllday.zhdy.model         # 所有 entity 别名类所在宝
  mapper-locations: mybatis/mapper/**/*.xml            # mapper 所在映射文件

spring:
  application:
    name: SPRING-CLOUD2019-SSO
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql 驱动包
    url: jdbc:mysql://155.94.235.33/cloud2019_db_sso    # 数据库名称
    username: root
    password: Root_12root
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数
      initial-size: 5                                  # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                             # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud2019-sso-8001      # 修改微服务名称
    prefer-ip-address: true                # 设置ip地址访问


info:
  app.name: spring-cloud2019-sso-8001
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$